#! /bin/sh
#
# Copyright 2011 Kevin McIntire, Gianluca Filippini
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not 
# use this file except in compliance with the License. You may obtain a copy 
# of the License at 
#
#    http://www.apache.org/licenses/LICENSE-2.0 
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#
# start / stop script for mongodb
#
# mongodb - this script starts and stops the mongo daemon
#
# chkconfig:   - 85 15 
# description:  Mongodb
# processname: mongod
# config:      /etc/sysconfig/mongodb
# pidfile:     /var/run/mongod.pid
. /etc/init.d/functions
# Source function library.
#. /lib/lsb/init-functions
# Source networking configuration.
. /etc/sysconfig/network
 
# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0
 
retval=0
pidfile=/var/run/mongod-slave.pid
MONGO_DIR="/usr/local/src/mongodb-linux-i686-1.0.0"
exec="${MONGO_DIR}/bin/mongod"
prog="mongod-slave"
lockfile="${MONGO_DIR}/lock/mongod-slave"
DBPATH=/mnt/output/db
MONGO_USER=mongodb
MONGO_OPTS="--dbpath $DBPATH --slave --source localhost:27017 --port 27018"

[ -f /etc/sysconfig/mongodb ] && . /etc/sysconfig/mongodb

start() {
    [ -x $exec ] || exit 5
    echo "Starting mongoDB daemon"
    daemon --pidfile pidfile --user $MONGO_USER \
        "$exec $MONGO_OPTS run" >> /var/log/mongodb-slave.log 2>&1 &
    return $?
}

stop() {
    echo "Stopping mongoDB daemon"
    killproc -d 10 $exec
    
    return $?
}

restart() {
    stop
    start
}

reload() {
    restart
}

rh_status() {
    status $prog
}
 
rh_status_q() {
    rh_status >/dev/null 2>&1
}
 
case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart|condrestart|try-restart}"
        exit 2
esac
